// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlpdNQqMEkQBqdEm-Ccjbu6Dg1GcnNDco',
    appId: '1:735848897125:web:2b9306d61138109a7b048c',
    messagingSenderId: '735848897125',
    projectId: 'extracted-b9462',
    authDomain: 'extracted-b9462.firebaseapp.com',
    storageBucket: 'extracted-b9462.appspot.com',
    measurementId: 'G-FBFEVK63LH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNADs83zQrGs5lHMRbdci4V1nCRsQZ83U',
    appId: '1:735848897125:android:4dbd9b454936dda67b048c',
    messagingSenderId: '735848897125',
    projectId: 'extracted-b9462',
    storageBucket: 'extracted-b9462.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk6UPmxFfzdJ94V_NxUkq8fmfKttgyCzI',
    appId: '1:735848897125:ios:9d2514446504822e7b048c',
    messagingSenderId: '735848897125',
    projectId: 'extracted-b9462',
    storageBucket: 'extracted-b9462.appspot.com',
    iosBundleId: 'com.example.extractedInformation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk6UPmxFfzdJ94V_NxUkq8fmfKttgyCzI',
    appId: '1:735848897125:ios:9d2514446504822e7b048c',
    messagingSenderId: '735848897125',
    projectId: 'extracted-b9462',
    storageBucket: 'extracted-b9462.appspot.com',
    iosBundleId: 'com.example.extractedInformation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlpdNQqMEkQBqdEm-Ccjbu6Dg1GcnNDco',
    appId: '1:735848897125:web:eb62d13893d39c767b048c',
    messagingSenderId: '735848897125',
    projectId: 'extracted-b9462',
    authDomain: 'extracted-b9462.firebaseapp.com',
    storageBucket: 'extracted-b9462.appspot.com',
    measurementId: 'G-0Y0MG2TV7G',
  );
}
